{
    "name" : "Hotel data",
    "author" : "Anubhav Jain",
    "version" : "1.0.0",
    "sequence" : -100,
    "category" : "Hotel management",
    "website" : "www.hotel.com",
    "summary" : "This model is about hotel info",
    "depends" : ['base','mail'],
    "data" : ["security/ir.model.access.csv",
              "views/menu.xml",
              "wizard/customer_wizard.xml",
              "wizard/create_room_wizard.xml",
              "views/customer_view.xml",
              "views/room_view.xml",
              "views/staff_view.xml",
              "views/housekeeping_view.xml",
              "reports/report.xml",
              "reports/staff_report.xml",
              "reports/customer_report.xml",
              "data/sequence.xml",
              "data/schedular_birthday.xml",
              ],
    "demo" : [],
    "installable" : True,
    "auto_install" : False,
    "license" : "LGPL-3",
}